Exercise on Functions:
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [6]:
def convert_units(conversion_type, value):
  """Converts between different units of measurement.

  Args:
    conversion_type: The type of conversion to perform (e.g., "length", "weight", "volume").
    value: The value to be converted.

  Returns:
    The converted value, or an error message if the conversion is invalid.
  """
  try:
    value = float(value)
  except ValueError:
    return "Invalid input. Please enter a numeric value."

  if conversion_type == "length":
    conversion_option = input("Enter conversion option (m_to_ft or ft_to_m): ").lower()
    if conversion_option == "m_to_ft":
      return value * 3.28084
    elif conversion_option == "ft_to_m":
      return value / 3.28084
    else:
      return "Invalid length conversion option."
  elif conversion_type == "weight":
    conversion_option = input("Enter conversion option (kg_to_lbs or lbs_to_kg): ").lower()
    if conversion_option == "kg_to_lbs":
      return value * 2.20462
    elif conversion_option == "lbs_to_kg":
      return value / 2.20462
    else:
      return "Invalid weight conversion option."
  elif conversion_type == "volume":
    conversion_option = input("Enter conversion option (l_to_gal or gal_to_l): ").lower()
    if conversion_option == "l_to_gal":
      return value * 0.264172
    elif conversion_option == "gal_to_l":
      return value / 0.264172
    else:
      return "Invalid volume conversion option."
  else:
    return "Invalid conversion type."

if __name__ == "__main__":
  conversion_type = input("Enter conversion type (length, weight, or volume): ").lower()
  value = input("Enter the value to convert: ")
  result = convert_units(conversion_type, value)
result


Enter conversion type (length, weight, or volume): weight
Enter the value to convert: 60
Enter conversion option (kg_to_lbs or lbs_to_kg): kg_to_lbs


132.2772

Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [8]:
def calculate_sum(numbers):
  """Calculates the sum of a list of numbers.

  Args:
    numbers: A list of numbers.

  Returns:
    The sum of the numbers, or an error message if the input is invalid.
  """
  try:
    return sum(numbers)
  except TypeError:
    return "Invalid input. Please enter a list of numbers."

def calculate_average(numbers):
  """Calculates the average of a list of numbers.

  Args:
    numbers: A list of numbers.

  Returns:
    The average of the numbers, or an error message if the input is invalid.
  """
  try:
    return sum(numbers) / len(numbers)
  except ZeroDivisionError:
    return "Cannot calculate the average of an empty list."
  except TypeError:
    return "Invalid input. Please enter a list of numbers."

def find_maximum(numbers):
  """Finds the maximum value in a list of numbers.

  Args:
    numbers: A list of numbers.

  Returns:
    The maximum value in the list, or an error message if the input is invalid.
  """
  try:
    return max(numbers)
  except ValueError:
    return "Invalid input. Please enter a list of numbers."

def find_minimum(numbers):
  """Finds the minimum value in a list of numbers.

  Args:
    numbers: A list of numbers.

  Returns:
    The minimum value in the list, or an error message if the input is invalid.
  """
  try:
    return min(numbers)
  except ValueError:
    return "Invalid input. Please enter a list of numbers."

if __name__ == "__main__":
  operation = input("Enter operation (sum, average, maximum, minimum): ").lower()
  try:
    numbers_str = input("Enter a list of numbers separated by spaces: ")
    numbers = [float(x) for x in numbers_str.split()]
  except ValueError:
    print("Invalid input. Please enter numbers separated by spaces.")
  else:
    if operation == "sum":
      result = calculate_sum(numbers)
    elif operation == "average":
      result = calculate_average(numbers)
    elif operation == "maximum":
      result = find_maximum(numbers)
    elif operation == "minimum":
      result = find_minimum(numbers)
    else:
      result = "Invalid operation."

result


Enter operation (sum, average, maximum, minimum): average
Enter a list of numbers separated by spaces: 2 3 4 5


3.5

Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [9]:
def extract_every_other(lst):
  return lst[::2]
# Example usage
my_list = [1, 2, 3, 4, 5, 6]
result_list = extract_every_other(my_list)
result_list


[1, 3, 5]

Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [12]:
def get_sublist(lst,start,end):
  return lst[start:end+1]

my_list=[1,2,3,4,5,6]
start_index=2
end_index=4
sub_list = get_sublist(my_list, start_index, end_index)
sub_list

[3, 4, 5]

3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [13]:
def reverse_list(lst):
  return lst[::-1]
my_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(my_list)
reversed_list


[5, 4, 3, 2, 1]

4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [14]:
def remove_first_last(lst):
  """Removes the first and last elements of a list and returns the resulting sublist.

  Args:
    lst: The input list.

  Returns:
    A sublist without the first and last elements, or the original list if it has less than 2 elements.
  """
  if len(lst) < 2:
    return lst
  return lst[1:-1]

# Example usage
my_list = [1, 2, 3, 4, 5]
sub_list = remove_first_last(my_list)
print(sub_list)  # Output: [2, 3, 4]


[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [15]:
def get_first_n(lst, n):
  """Extracts the first n elements from a list.

  Args:
    lst: The input list.
    n: The number of elements to extract.

  Returns:
    A list containing the first n elements of the input list.
    Returns the entire list if n is greater than or equal to the list's length.
    Returns an empty list if n is zero or negative, or if the input list is empty.
  """
  if not lst or n <=0:
      return []
  return lst[:n]
#Example
my_list = [1, 2, 3, 4, 5]
n = 3
first_n_elements = get_first_n(my_list, n)
first_n_elements

[1, 2, 3]

6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [21]:
def get_last_n(lst, n):
  """Extracts the last n elements of a list using slicing.

  Args:
    lst: The input list.
    n: The number of elements to extract from the end.

  Returns:
    A list containing the last n elements of the input list.
    Returns an empty list if n is zero or negative, or if the input list is empty.
    Returns the entire list if n is greater than or equal to the list's length.
  """
  if not lst or n <= 0:
    return []
  return lst[-n:]
my_list = [1, 2, 3, 4, 5]
result = get_last_n(my_list, 2)
print(result)

[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [22]:
def reverse_skip(lst):
  """
  Extracts a list of elements in reverse order starting from the second-to-last
  element and skipping one element in between.

  Args:
    lst: The input list.

  Returns:
    A new list containing every second element starting from the second-to-last,
    moving backward.
  """
  return lst[-2::-2]

# Example usage
my_list = [1, 2, 3, 4, 5, 6]
result_list = reverse_skip(my_list)
print(result_list)


[5, 3, 1]


Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [23]:
def flatten(lst):
  """Flattens a nested list into a single list.

  Args:
    lst: The nested list to flatten.

  Returns:
    A new list containing all elements from the nested list in a single dimension.
  """
  flattened_list = []
  for sublist in lst:
    if isinstance(sublist, list):
      flattened_list.extend(flatten(sublist))  # Recursive call for nested lists
    else:
      flattened_list.append(sublist)
  return flattened_list

# Example usage
nested_list = [[1, 2], [3, 4], [5]]
flat_list = flatten(nested_list)
print(flat_list)


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [24]:
def access_nested_element(lst, indices):
  """
  Extracts a specific element from a nested list given its indices.

  Args:
    lst: The nested list.
    indices: A list of indices specifying the element's position.

  Returns:
    The element at the specified position, or None if the indices are invalid.
  """
  element = lst
  for index in indices:
    try:
      element = element[index]
    except (IndexError, TypeError):
      return None
  return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(lst, indices)
print(result)

6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [26]:
def sum_nested(lst):
  """Calculates the sum of all numbers in a nested list.

  Args:
    lst: The nested list.

  Returns:
    The sum of all numbers in the list.
  """
  total_sum = 0
  for element in lst:
    if isinstance(element, list):
      total_sum += sum_nested(element)  # Recursive call for nested lists
    elif isinstance(element, int) or isinstance(element, float):
      total_sum += element
  return total_sum

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)  # Output: 21

21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [30]:
def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list.

    Args:
        lst: The nested list.
        elem: The element to remove.

    Returns:
        The modified list with all occurrences of the element removed.
    """
    new_list = []
    for sublist in lst:
        new_sublist = []
        for item in sublist:
            if item != elem:
                new_sublist.append(item)
        new_list.append(new_sublist)
    return new_list  # This returns the modified list

nested_list = [[1, 2, 3], [4, 2, 6], [7, 2, 9]]
element_to_remove = 2

# Call the function and print the result
result = remove_element(nested_list, element_to_remove)
print(result)

[[1, 3], [4, 6], [7, 9]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [32]:
def find_max(lst):
    """Finds the maximum element in a nested list.

    Args:
        lst: The nested list.

    Returns:
        The maximum element in the list.
    """
    max_element = float('-inf')  # Initialize with negative infinity

    def _find_max(sub_lst):
        nonlocal max_element
        for element in sub_lst:
            if isinstance(element, list):
                _find_max(element)  # Recursive call for nested lists
            elif isinstance(element, (int, float)):
                max_element = max(max_element, element)

    _find_max(lst)
    return max_element

nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)

6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [39]:
def count_occurrences(lst, elem):
    """Counts the occurrences of an element in a nested list.

    Args:
        lst: The nested list.
        elem: The element to count.

    Returns:
        The number of times the element appears in the list.
    """
    count = 0
    for sublist in lst:
        if isinstance(sublist, list):  # Check if it's a sublist
            count += count_occurrences(sublist, elem)  # Recursive call
        elif sublist == elem:  # Direct match
            count += 1
    return count

# Example usage
nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2  # Specify the element to count

# Call the function correctly
result = count_occurrences(nested_list, element_to_count)
print(result)

3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [43]:
def deep_flatten(lst):
    """Flattens a list of lists of lists into a single list.

    Args:
        lst: The deeply nested list.

    Returns:
        A single flattened list.
    """
    flattened_list = []
    for element in lst:
        if isinstance(element, list):
            flattened_list.extend(deep_flatten(element))
        else:
            flattened_list.append(element)
    return flattened_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [46]:
def average_nested(lst):
    """Calculates the average of all elements in a nested list.

    Args:
        lst: The nested list.

    Returns:
        The average of all elements in the list, or 0 if the list is empty or contains no numbers.
    """
    total_sum = 0
    count = 0
    for sublist in lst:
        for element in sublist:
            if isinstance(element, (int, float)):
                total_sum += element
                count += 1
    return total_sum / count if count else 0

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
result = average_nested(nested_list)
print(result)

5.0


To - Do - NumPy
Please complete all the problems listed below:
10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [47]:
import numpy as np

# 1. Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))
print("Empty array:\n", empty_array)

# 2. Initialize an all one array with size 4X2.
ones_array = np.ones((4, 2))
print("Ones array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value.
fill_array = np.full((3, 3), 7)  # Example: Filled with 7
print("Fill array:\n", fill_array)

# 4. Return a new array of zeros with the same shape and type as a given array.
example_array = np.array([[1, 2], [3, 4]], dtype=float)
zeros_like_array = np.zeros_like(example_array)
print("Zeros like array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array.
ones_like_array = np.ones_like(example_array)
print("Ones like array:\n", ones_like_array)

# 6. For an existing list new_list = [1, 2, 3, 4] convert to a numpy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy array from list:\n", numpy_array)

Empty array:
 [[5.0261283e-316 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Fill array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros like array:
 [[0. 0.]
 [0. 0.]]
Ones like array:
 [[1. 1.]
 [1. 1.]]
Numpy array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [49]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49.
array_1 = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8.
matrix_2 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:\n", matrix_2)

# 3. Create a 3x3 identity matrix.
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array:\n", random_array)
print("Mean of random array:\n", mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum.
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("10x10 random matrix:\n", random_matrix)
print("Minimum value:\n", min_value)
print("Maximum value:\n", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4)
print("Zero array with 5th element replaced:\n", zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside.
size = 5  # Example size
array_8 = np.ones((size, size))
array_8[1:-1, 1:-1] = 0
print("2D array with 1 on border and 0 inside:\n", array_8)


# 9. Create an 8x8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1
print("Checkerboard pattern:\n", checkerboard)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array:
 [0.91649565 0.31964244 0.85809829 0.72840304 0.33557679 0.87690114
 0.49883332 0.33906096 0.66639163 0.97173916 0.90168069 0.76315966
 0.24468474 0.31014675 0.17346262 0.94190379 0.63523927 0.63789246
 0.82812172 0.81441789 0.25197178 0.33986437 0.70312604 0.05130211
 0.12356511 0.43340401 0.56787033 0.19570777 0.00372266 0.50502055]
Mean of random array:
 0.5312468911003247
10x10 random matrix:
 [[0.14824867 0.11112073 0.99989836 0.78110221 0.98865676 0.50484721
  0.12751057 0.99688208 0.35899421 0.414181  ]
 [0.68928447 0.92216068 0.63193073 0.57723589 0.31897959 0.42090797
  0.59205368 0.66207357 0.98238384 0.9733295 ]
 [0.0572246  0.08813603 0.7533907  0.35434639 0.73438722 0.24231855
  0.72

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [54]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays.
print("Sum of x and y:\n", x + y)

# 2. Subtract the two arrays.
print("Difference of x and y:\n", x - y)

# 3. Multiply the array with an integer.
print("x multiplied by 3:\n", x * 3)

# 4. Find the square of each element of the array.
print("Square of each element in x:\n", x**2)

# 5. Dot products.
print("Dot product of v and w:\n", np.dot(v, w))
print("Dot product of x and v:\n", np.dot(x, v))
print("Dot product of x and y:\n", np.dot(x, y))

# 6. Concatenate x and y along rows
print("Concatenate x and y along rows:\n", np.concatenate((x, y), axis=0))

# 7. Concatenate v and w along columns (Stack vertically)
print("Concatenate v and w along columns:\n", np.vstack((v, w)))

# 8. Fixing concatenation of x and v
try:
    # Reshaping `v` to have a second dimension (column vector)
    v_reshaped = v.reshape(2, 1)

    # Concatenating x and v_reshaped along axis=1 (columns)
    print("Concatenate x and v (reshaped to 2,1) along columns:\n", np.concatenate((x, v_reshaped), axis=1))
except ValueError as e:
    print(f"Error: {e}")
    print("Explanation: Cannot concatenate arrays with inconsistent dimensions.")
    print("You must reshape v before concatenation: `v.reshape(2,1)` to match x's shape.")

Sum of x and y:
 [[ 6  8]
 [10 13]]
Difference of x and y:
 [[-4 -4]
 [-4 -3]]
x multiplied by 3:
 [[ 3  6]
 [ 9 15]]
Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w:
 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]
Concatenate x and v (reshaped to 2,1) along columns:
 [[ 1  2  9]
 [ 3  5 10]]


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [51]:
import numpy as np

# Problem 4: Matrix Operations

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A.A⁻¹ = \n", I)  # Should be close to the identity matrix

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print("BA = \n", BA)
print("AB != BA:", not np.array_equal(AB, BA))

# 3. Prove (AB)ᵀ = BᵀAᵀ
AB_transpose = np.transpose(AB)
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BT_AT = np.dot(B_transpose, A_transpose)
print("(AB)ᵀ = \n", AB_transpose)
print("BᵀAᵀ = \n", BT_AT)
print("(AB)ᵀ == BᵀAᵀ:", np.array_equal(AB_transpose, BT_AT))

# Solve the system of linear equations using inverse method
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
X = np.dot(np.linalg.inv(A), B)
print("Solution using inverse method:\n",X)

# Solve using np.linalg.solve
X = np.linalg.solve(A, B)
print("Solution using np.linalg.solve:\n",X)

A.A⁻¹ = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
AB != BA: True
(AB)ᵀ = 
 [[23 51]
 [13 29]]
BᵀAᵀ = 
 [[23 51]
 [13 29]]
(AB)ᵀ == BᵀAᵀ: True
Solution using inverse method:
 [ 2.  1. -2.]
Solution using np.linalg.solve:
 [ 2.  1. -2.]
